#!/bin/bash

level=$(awk 'NR==3 {print $3}' /proc/net/wireless | jq tonumber)
if [ -z "$level" ]; then
level=0
fi

status=$(iwctl station wlan0 show | grep -oP '^\s*State\s+\K\S+' | jq -R 'if . == "disconnected" then 0 else 1 end')

website="www.google.com"
ping -c 1 $website > /dev/null
if [ $? -eq 0 ]; then
    internet=1
else
    internet=0
fi

echo "{\"level\":$level, \"status\":$status, \"internet\":$internet}" | jq '{level, status, internet}'
