#!/bin/bash

level=$(awk 'NR==3 {print $3}' /proc/net/wireless | jq tonumber)
if [ -z "$level" ]; then
level=0
fi

status=$(nmcli -t -f GENERAL.STATE device show wlp0s20f3 | grep -q ":30" && echo 0 || echo 1)

website="www.google.com"
ping -c 1 $website > /dev/null
if [ $? -eq 0 ]; then
    internet=1
else
    internet=0
fi

echo "{\"level\":$level, \"status\":$status, \"internet\":$internet}" | jq '{level, status, internet}'
