hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("hyprlock")
    hl.exec_cmd("mako")
    hl.exec_cmd("aw-qt")
    hl.exec_cmd("~/.cargo/bin/aw-watcher-window-hyprland")
    hl.exec_cmd("eww open bar")
    hl.exec_cmd("hypridle")
end)

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("OZONE_PLATFORM", "wayland")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
hl.env("QT_QPA_PLATFORMTHEME", "gtk3")
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__NV_PRIME_RENDER_OFFLOAD", "0")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("AQ_DRM_DEVICES", "/dev/dri/card0:/dev/dri/card1")
