-- Generated by nwg-displays on 2026-07-01 at 10:14:14. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2880x1800@120.0",
    position = "0x540",
    scale = 2.0
})
hl.monitor({
    output = "DP-1",
    mode = "3840x2160@60.0",
    position = "1440x0",
    scale = 1.5
})
