-- Generated by nwg-displays on 2026-05-23 at 10:26:30. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "DP-1",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "DP-1"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "eDP-1",
    default = true
})
hl.workspace_rule({
    workspace = "4",
    monitor = "eDP-1"
})
